import type { Metadata } from "next";
import "./globals.css";
import AuthContext from "@/providers/SessionProvider";
import { ToastProvider } from "@/providers/ToastProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="per" dir="rtl">
      <body className="flex flex-col w-full h-screen ">
        <AuthContext>
          <ToastProvider />
          <Navbar />
          <main className="flex-1 flex-shrink px-0 2xl:container">
            {children}
          </main>
          <Footer />
        </AuthContext>
      </body>
    </html>
  );
}
